spring:
    profiles:
        active: dev

#user info
user:
    id: 1
    username: zhaojigang
    password: 123

#redis cluster
redis:
    cache:
        clusterNodes: localhost:8080
        commandTimeout: 5
        expireSeconds: 120

mybatis:
    typeAliases:
        package: com.hzm.boot.domain
    mapper:
        locations: classpath:mapper/*.xml

server:
    port: 9090

#jdbc
jdbc:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytestdb?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: vvvxxx