spring:
    profiles:
        active: product
    redis:
        host: 127.0.0.1
        port: 6379
        database: 0
        pool:
            max-idle: 8
            min-idle: 0
            max-active: 8
            max-wait: -1


server:
    port: 9090

#user info
user:
    id: 1
    username: zhaojigang
    password: 123

#redis cluster
redis:
    cache:
        clusterNodes: 127.0.0.1:6379
        commandTimeout: 5
        expireSeconds: 120


mybatis:
    typeAliases:
        package: com.hzm.boot.domain
    mapper:
        locations: classpath:mapper/*.xml


#jdbc
jdbc:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytestdb?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: vvvxxx

